import { TOPICS } from "./constants";

export default [
  {
    topicName: TOPICS.JAVASCRIPT_QUESTIONS,
    position: 0,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Topic: TOPICS.JAVASCRIPT_QUESTIONS,
        Problem: "What is closure",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "javascript.info",
      },
    ],
  },
  {
    topicName: TOPICS.CODING_QUESTIONS,
    position: 1,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "How to merge objects in javascript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/how-to-merge-objects-in-javascript",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Compare two array or object with JavaScript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/array/compare-two-array-or-object-with-javascript/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "What is debouncing in javascript?.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/what-is-debouncing-in-javascript/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "What is throttling in javascript?.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/what-is-throttling-in-javascript/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Detect idle state (inactive) in Javascript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/detect-idle-state-inactive-in-javascript",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Currying in JavaScript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/currying-in-javascript-part-1/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem:
          "Capture product visible on viewport when user stops scrolling.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/capture-product-visible-on-viewport-when-user-stops-scrolling/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Animate elements in a sequence.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/animate-elements-in-a-sequence/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Create Pausable auto incrementer.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/create-pausable-auto-incrementer",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Implement clearAllTimeout in JavaScript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/implement-clearalltimeout-in-javascript/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Implement ClearAllInterval in JavaScript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/implement-clearallinterval-in-javascript/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Singleton design pattern in JavaScript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/singleton-design-pattern-in-javascript/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Observer design pattern in JavaScript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/observer-design-pattern-in-javascript",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Remove cycle from the object in JavaScript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/remove-cycle-from-the-object-in-javascript",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Execute async functions in Series.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/execute-async-functions-in-series/",
      },
      {
        Topic: TOPICS.CODING_QUESTIONS,
        Problem: "Retry promises N number of times in JavaScript.",
        Done: false,
        Bookmark: false,
        Notes: "",
        URL: "https://learnersbucket.com/examples/interview/retry-promises-n-number-of-times-in-javascript/",
      },
    ],
  },
];
export const version = 100000022;
